version: '3.4'

services:
  foodshop.web:
    image: ${DOCKER_REGISTRY-}foodshopweb
    build:
      context: .
      dockerfile: FoodShop.Web/Dockerfile
    networks:
      - foodshopnetwork

  foodshop.api.catalog:
    image: ${DOCKER_REGISTRY-}foodshopapicatalog
    build:
      context: .
      dockerfile: FoodShop.Api.Catalog/Dockerfile
    networks:
      - foodshopnetwork

  sqldata:
    container_name: sqlserverft
    build:
      dockerfile: sqlserver-fulltext.Dockerfile
    ports:
      - "5433:1433"
    environment:
      SA_PASSWORD: "Pass@word"
      ACCEPT_EULA: "Y"
    networks:
      - foodshopnetwork

  basketdata:
    image: redis:alpine
    networks:
      - foodshopnetwork

networks:
  foodshopnetwork: