version: '3.4'

services:

  foodshop.api.basket:
    image: ${DOCKER_REGISTRY-}foodshopapibasket
    build:
      context: .
      dockerfile: FoodShop.Api.Basket/Dockerfile
    ports:
      - "13080:80"
      - "13443:443"
    networks:
      - foodshopnetwork

  foodshop.api.order:
    image: ${DOCKER_REGISTRY-}foodshopapiorder
    depends_on:
      - messaging
    build:
      context: .
      dockerfile: FoodShop.Api.Order/Dockerfile
    ports:
      - "14080:80"
      - "14443:443"
    networks:
      - foodshopnetwork

  foodshop.api.customerprofile:
    image: ${DOCKER_REGISTRY-}foodshopapicustomerprofile
    build:
      context: .
      dockerfile: FoodShop.Api.CustomerProfile/Dockerfile
    ports:
      - "12080:80"
      - "12443:443"
    networks:
      - foodshopnetwork

  foodshop.api.auth:
    image: ${DOCKER_REGISTRY-}foodshopapiauth
    build:
      context: .
      dockerfile: FoodShop.Api.Auth/Dockerfile
    ports:
      - "11080:80"
      - "11443:443"
    networks:
      - foodshopnetwork

  foodshop.api.catalog:
    image: ${DOCKER_REGISTRY-}foodshopapicatalog
    build:
      context: .
      dockerfile: FoodShop.Api.Catalog/Dockerfile
    ports:
      - "10080:80"
      - "10443:443"
      - "10090:90"
    networks:
      - foodshopnetwork

  foodshop.api.warehouse:
    image: ${DOCKER_REGISTRY-}foodshopapiwarehouse
    build:
      context: .
      dockerfile: FoodShop.Api.Warehouse/Dockerfile
    ports:
      - "15080:80"
      - "15443:443"
    networks:
      - foodshopnetwork

  sqldata:
    container_name: sqlserverft
    build:
      dockerfile: sqlserver-fulltext.Dockerfile
    ports:
      - "5433:1433"
    environment:
      SA_PASSWORD: "Pass@word"
      ACCEPT_EULA: "Y"
    networks:
      - foodshopnetwork

  basketdata:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - foodshopnetwork

  messaging:
    image: rabbitmq:3-management-alpine
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - foodshopnetwork

networks:
  foodshopnetwork: